---
- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: install nginx
  apt:
    name: nginx
    state: latest
- name: inatall php
  apt:
    pkg:
    - php-fpm
- name: copy index.php
  copy:
    src: "{{ role_path }}/files/index.php"
    dest: /var/www/html/index.php
- name: upload nginx default config
  copy:
    src: "{{ role_path }}/files/app.conf"
    dest: /etc/nginx/sites-available/default
- name: enable nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
- name: enable php-fpm
  systemd:
    name: php7.4-fpm
    state: started
    enabled: yes
