---
- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install haproxy
  apt:
    name: haproxy
    state: present
- name: configure haproxy
  template:
    dest: /etc/haproxy/haproxy.cfg
    src: templates/haproxy.cfg.j2
- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
    enabled: yes