---
- hosts: webservers
  gather_facts: yes
  vars:
    package_list:
      - nginx
      - php-fpm

  tasks:
   - name: Update apt cache
     apt:
      update_cache: yes
      cache_valid_time: 7200
     become: yes

   - name: Install packages
     apt:
      name: "{{ item }}"
      state: present
     loop: "{{ package_list }}"
     become: yes

   - name: start nginx
     service:
         name: nginx
         state: started
     become: yes

   - name: copy the nginx config file
     template:
       src: templates/nginx.cfg.j2  
       dest: /etc/nginx/sites-available/default
     become: yes

   - name: create symlink
     file:
       src: /etc/nginx/sites-available/default
       dest: /etc/nginx/sites-enabled/default
       state: link
     become: yes

   - name: copy php file
     copy:
       src: templates/index.php
       dest: /var/www/html/
     become: yes

   - name: restart nginx
     service:
       name: nginx
       state: restarted
     become: yes

- hosts: haproxy
  gather_facts: yes
  vars:
    haproxy_mode: http
    haproxy_algorithm: roundrobin
    haproxy_option: forwardfor
    haproxy_backend: webservers
  become: yes

  tasks:
   - name: Update apt cache in Haproxy
     apt:
      update_cache: yes
      cache_valid_time: 7200
     become: yes

   - name: Install haproxy
     apt:
      name: haproxy
      state: present
     become: yes

   - name: Update HAProxy config file
     template:
      src: templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
     become: yes

   - name: Restart HAProxy
     service:
       name: haproxy
       state: restarted
     become: yes